### ISSUE TITLE
User specific crowdin.yaml doesn't support base_path

### ISSUE THREAD

**Issue by mikeNG** [crowdin/crowdin-cli-v1#16]
As in #15, using an absolute path as base_path is not the correct solution. I guess it's easy to add support for base_path in the user-specific yaml file, like we can currently do with api_key.

This is needed for our project (CyanogenMod) since a lot of people use the script checked out in different locations.

**Comment by allaire** [comment]
:+1:

**Comment by allaire** [comment]
It just worked for me using something like `base_path: ./config/locales`
