### ISSUE TITLE
API Credentials from environment variables

### ISSUE THREAD

**Issue by metade** [crowdin/crowdin-cli-v1#18]
In our application we use environment variables for storing sensitive credentials.

It would be great if the crowdin.yaml file could support ERB so that we could load the API key from an environment variable, e.g.

```
api_key: <%= ENV["CROWDIN_API_KEY"] %>
```

**Comment by GreatWizard** [comment]
:+1: This is a very good idea!

**Comment by mamantoha** [comment]
:+1: This feature will appear in the next version

**Comment by mamantoha** [comment]
This feature is not compatible with the Python version of crowdin-cli.
Who cares? :smile:

**Comment by amessinger** [comment]
Ehhhh, I guess that I do :(

**Comment by GreatWizard** [comment]
Maybe we can use alternate keys like `api_key_env` and `project_identifier_env`.
Then, the cli tool can use any method it wants to get the environment variables?
And this is possible for https://github.com/PaulGregor/crowdin-cli to do the update more easily :-)

**Comment by mamantoha** [comment]
We invite @PaulGregor here :) What do you think?

**Comment by PaulGregor** [comment]
Sure, no problem. In next release Python Cli will look for API keys in environment variables,  if key has not been defined in config.

**Comment by mamantoha** [comment]
`api_key_env` and `project_identifier_env` should identify ENV names for those variables. Right?

**Comment by GreatWizard** [comment]
To summarize the discussion...
- All in config file:
  
  ```
  api_key: xxx
  project_identifier: yyy
  ```
- All in environment variables:
  
  ```
  api_key_env: CROWDIN_API_KEY
  project_identifier_env: CROWDIN_PROJECT
  ```
- If mix, `api_key` and `project_identifier` have priority:
  
  ```
  api_key_env: CROWDIN_API_KEY              ## Loser
  project_identifier_env: CROWDIN_PROJECT   ## Loser
  api_key: xxx                              ## Winner
  project_identifier: yyy                   ## Winner
  ```

Right ?

**Comment by mamantoha** [comment]
:+1: looks good to me
