### ISSUE TITLE
How to specify a target folder on Crowdin and how to keep local hierarchy?

### ISSUE THREAD

**Issue by mamantoha** [crowdin/crowdin-cli-v1#4]

**Comment by mamantoha** [comment]
how to keep local hierarchy?

commit: 31473fab7f59b02b40b7126e0dab9fcf0e3f9339

**Comment by allaire** [comment]
@mamantoha And how to specify a target folder on Crowdin? I want to upload each of my translation files in different parent directories on Crowdin (i.e web/, ios/, etc.) but I don't want to upload local hierarchy (adding a web/ folder in config/locales/ wouldn't make much sense)

**Comment by SinisaG** [comment]
@allaire - You figured out how to specify target folder on upload? It was some time ago..but still... :)

**Comment by SinisaG** [comment]
For record, I solved it bu adding 

```
preserve_hierarchy: true
```

And then setting dest.
