### ISSUE TITLE
Download command should create directories and folder when they does not exist

### ISSUE THREAD

**Issue by thromera** [crowdin/crowdin-cli-v1#42]
Use case : 
I add a new translation language from Crowdin website, and do the translations. When a developer use the `crowdin-cli download`, the new language folder won't exist yet, and the command won't create folders / files associated. It should be the case to simplify workflow and avoid developer to create a multitude of files / folders to match the new locale.

**Comment by mamantoha** [comment]
Hi @Erowlin,

I'm not able to reproduce this issue on my side 
Please provide you config file. Thanks.

**Comment by thromera** [comment]
It was a configuration problem, I confirm crowdin create the correct directories when needed.

Thank you.
