### ISSUE TITLE
Is there a way to exclude source directories?

### ISSUE THREAD

**Issue by gka** [crowdin/crowdin-cli-v1#5]
We are translating a software that is divided into a core and several plugins. Some of the plugins are treated as 'core plugins' and some are not. The core plugins should be translated on Crowdin, so I added the corresponding regex to the yaml config (e.g. `plugins/**/locale/messages.json`).

Is there currently a way to specify certain URL patterns to be excluded or ignored from crowdin-cli, comparably to the [.git/info/exclude](https://help.github.com/articles/ignoring-files#repository-exclude) file?

**Comment by mamantoha** [comment]
There is no way to exclude some directories in the project.

**Comment by mamantoha** [comment]
We realize this possibility in the next couple days.

**Comment by mamantoha** [comment]
https://github.com/crowdin/crowdin-cli#ignoring-directories

1dfbe5c69e64282c59606b9b3b3c82a1f6256a80

**Comment by gka** [comment]
Thanks a lot! +1
