### ISSUE TITLE
Tags with version numbers

### ISSUE THREAD

**Issue by banesto** [crowdin/crowdin-cli-v1#51]
Thanks for the project!

I would really appreciate if you could add tags to mark release versions - that would ease searching and making diffs.

**Comment by mamantoha** [comment]
Can you please clarify this a little bit more?

**Comment by banesto** [comment]
See [this](https://github.com/rails/rails/releases) for example. If you attach a tag to commit with a version there would be the ability to see all versions at once and get commit hash of each version which is really helpful to track changes between the versions.

**Comment by banesto** [comment]
I am particularly interested if I can update gem v0.2.2 to most recent one.

**Comment by mamantoha** [comment]
Hm... I think this should be implemented on Crowdin side. 

https://crowdin.com/contacts

**Comment by banesto** [comment]
That's a git feature - I've made the change on [my fork](https://github.com/banesto/crowdin-cli/releases) just now.

**Comment by mamantoha** [comment]
Sorry, I misunderstood you. You can create PR from your fork.

**Comment by banesto** [comment]
Well that's a tricky part - github says there are no code changes hence no PR could be created 😞

**Comment by banesto** [comment]
Maybe you can grant me rights to repo for this one push?

**Comment by mamantoha** [comment]
Try

```
git push origin --tags
```

**Comment by banesto** [comment]
Permission denied 😞

**Comment by mamantoha** [comment]
Well. I somehow added your remote repository and merge it into master. Thank you!

**Comment by banesto** [comment]
I've added all the other releases I could find. You can merge it once again!
