### ISSUE TITLE
Ruby 1.9 requires to install specific versions of dependencies

### ISSUE THREAD

**Issue by Wardormeur** [crowdin/crowdin-cli-v1#53]
We're using CircleCI for deployment/tests and we stumbled upon a problem this WE : we couldn't deploy because crowdin-cli wouldn't install.
We needed to add specific version of dependencies which upgraded, to not support 1.9 anymore
Use those lines (in CircleCI in a :before_deploy block) to restore a proper install, or restrict those in the GemFile :)
gem install mime-types -v 2.6.2
gem install rest-client -v 1.8
Cheers and keep it up !

**Comment by Andrulko** [comment]
Thank you very much for sharing all the details! We will make crowdin-cli work shortly.

**Comment by mamantoha** [comment]
Ruby 1.9.x is past its end of life and is now unsupported.
