### ISSUE TITLE
Error when using branches with slash

### ISSUE THREAD

**Issue by denzelem** [crowdin/crowdin-cli-v1#57]
If I try to upload a branch like `somehow/new-feature-branch` with `crowdin-cli upload sources -b somehow/new-feature-branch` I get the error:

```
Creating a new branch `somehow/new-feature-branch'error: 17: Specified directory was not found
```

**Comment by mamantoha** [comment]
You can not use `somehow/new-feature-branch` for the branch name. In Crowdin branch is similar to the directory.

**Comment by denzelem** [comment]
What do you think about mapping a branch like `somehow/new-feature-branch` to the directory name `somehow-new-feature-branch`?

**Comment by STRML** [comment]
I have been using the following in my scripts to get around this:

```
crowdin-cli upload sources -b "$(./scripts/getBranch.sh | sed 's/\\//-/')"
```

**Comment by axhamre** [comment]
What is Crowdin's proposed separator character for branch titles? Slash is somewhat a convention: https://stackoverflow.com/questions/273695/what-are-some-examples-of-commonly-used-practices-for-naming-git-branches

But as I understand it, Crowdin omits everything before `/` ?

**Comment by denzelem** [comment]
If someone wants to fix this issue and make a PR, feel free to re-open it.
