### ISSUE TITLE
support tcp keepalives

### ISSUE THREAD

**Issue by nathanhruby** [crowdin/crowdin-cli-v1#58]
When trying to download a large project that creates a new export, a request can take a long time (in the case that I am seeing ~60 minutes).  When this happens, the cli client keeps the connection open and expects it to remain intact while idle.  

This  doesn't work behind a lot of firewalls or NAT gateways that have idle connection time limits (AWS NAT Gateway specifically has a 5 min limit and is the one that triggered this issue for us). When this happens and the connection is drop'ed in the middle without a corresponding RST being sent (which is a separate kind of wrong) the client thinks the connection is still up and waits patiently forever to hear back from the remote.

Please support TCP keepalives for http connections in order to avoid this issue.  When inspecting the TCP socket the keepalive flag is not added.  For the short term we were able to work around the issue with https://github.com/flonatel/libdontdie

It looks like the HTTP handling comes from rest-client, which has a few keepalive patches that are not merged but currently no support for this feature.

**Comment by mamantoha** [comment]
This project is no longer being actively maintained. That doesn't mean that it's going away, though. You can try https://github.com/crowdin/crowdin-cli-2 and ask there to support TCP keepalives.

**Comment by nathanhruby** [comment]
opened a corresponding ticket in crowdin/crowdin-cli-2

I will leave this to close for a maintainer if there is no interest in this issue due to deprecation.

**Comment by mamantoha** [comment]
As you mentioned above https://github.com/rest-client/rest-client  no support for this feature. That's why I don't see an easy way to implement TCP keepalives here.
