### ISSUE TITLE
uploading translations - error: Unknown option --import-eq-suggestions

### ISSUE THREAD

**Issue by jklingen** [crowdin/crowdin-cli-v1#8]
Invoking
`java -jar crowdin-cli.jar upload --import-eq-suggestions translations`
returns an error message
`error: Unknown option --import-eq-suggestions`

Below it says (excerpt):

```
SYNOPSIS
    <script> [global options] upload [--auto-update] sources
    <script> [global options] upload [--auto-approve-imported] [--import-duplicates] [--import-eq-suggestions] [-l crowdin_language_code|--language crowdin_language_code] translations
```

Seems to be valid usage for me... has this option been removed?

Using crowdin-cli 0.25 downloaded from crowdin.net, on Windows 8, with Java 7.

**Comment by mamantoha** [comment]
Error in documentation

It will be right:

```
java -jar crowdin-cli.jar upload translations --import-eq-suggestions
```

**Comment by mamantoha** [comment]
Next major update will fix it.
Tnx :)

**Comment by jklingen** [comment]
Works like Charm, thanks :)
