### ISSUE TITLE
Split project configuration and user credentials

### ISSUE THREAD

**Issue by teoulas** [crowdin/crowdin-cli-v1#9]
Currently the crowdin.yaml file contains project-specific configuration and user credentials  (`api_key`). This means that you can't commit this file in the code repository, because the API key would leak to other users. It would be great if crowdin-cli would allow 2 configuration files:
- a user-specific, probably residing in $HOME/.crowdin.yaml
- a project-specific, residing in the project directory

**Comment by lipis** [comment]
+1

If the local crowdin.yaml exists then respect that one and if things are missing check in the home directory...

**Comment by mamantoha** [comment]
:+1:

**Comment by mamantoha** [comment]
added in 0.3.4

https://github.com/crowdin/crowdin-cli#split-project-configuration-and-user-credentials
